export let reactjsPosts = {
  "kind":"Listing",
  "data":{
    "modhash":"8uldkn7x59b539fd0541f994c64d446f70b534080f0666102f",
    "children":[
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey guys! Just wondering where is the best place to host a site made with react, node, gulp? I bought the site with godaddy but I don&amp;#39;t know of any plans godaddy offers that can let me code in these languages! Please help!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"Hey guys! Just wondering where is the best place to host a site made with react, node, gulp? I bought the site with godaddy but I don't know of any plans godaddy offers that can let me code in these languages! Please help!",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vslmv",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"MaskedBandit1",
          "media":null,
          "score":2,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":0,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":true,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vslmv/where_to_host_site_made_with_reactnodegulp/",
          "locked":false,
          "name":"t3_4vslmv",
          "created":1470175736.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vslmv/where_to_host_site_made_with_reactnodegulp/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Where to host site made with react,node,gulp",
          "created_utc":1470146936.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":2
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"builtvisible.com",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vs9q6",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"petewailes",
          "media":null,
          "score":2,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":0,
          "thumbnail":"default",
          "subreddit_id":"t5_2zldd",
          "hide_score":true,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vs9q6/dynamic_kml_layers_with_google_maps_javascript/",
          "locked":false,
          "name":"t3_4vs9q6",
          "created":1470171133.0,
          "url":"http://builtvisible.com/dynamic-kml-layers-with-google-maps-javascript-api/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Dynamic KML Layers with Google Maps Javascript API &amp; React",
          "created_utc":1470142333.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":2
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"egghead.io",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vnxg5",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"mweststrate",
          "media":null,
          "score":49,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/_T1URH8a7jKq5Vs1dVaHhFfzONPk4RvKI3u_WjpSWXE.jpg?s=d1303cc79837eef69a4fa44554e9e6ed",
                  "width":1200,
                  "height":400
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/_T1URH8a7jKq5Vs1dVaHhFfzONPk4RvKI3u_WjpSWXE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=4da7d0f749b1ea00c36d76901f00d7d3",
                    "width":108,
                    "height":36
                  },
                  {
                    "url":"https://i.redditmedia.com/_T1URH8a7jKq5Vs1dVaHhFfzONPk4RvKI3u_WjpSWXE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=dd3411e3eba854ab4beee4f7377a6e87",
                    "width":216,
                    "height":72
                  },
                  {
                    "url":"https://i.redditmedia.com/_T1URH8a7jKq5Vs1dVaHhFfzONPk4RvKI3u_WjpSWXE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=a0f9481cbb0653196b6595f386b34260",
                    "width":320,
                    "height":106
                  },
                  {
                    "url":"https://i.redditmedia.com/_T1URH8a7jKq5Vs1dVaHhFfzONPk4RvKI3u_WjpSWXE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=f65a07597919076b05e7e00f2d8e2a33",
                    "width":640,
                    "height":213
                  },
                  {
                    "url":"https://i.redditmedia.com/_T1URH8a7jKq5Vs1dVaHhFfzONPk4RvKI3u_WjpSWXE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=b22e6c556dd688ad99ac43e45f73b3f2",
                    "width":960,
                    "height":320
                  },
                  {
                    "url":"https://i.redditmedia.com/_T1URH8a7jKq5Vs1dVaHhFfzONPk4RvKI3u_WjpSWXE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=584f91845f7bef77be682540853d3eec",
                    "width":1080,
                    "height":360
                  }
                ],
                "variants":{

                },
                "id":"M1Xjq2Tz0qOqlIoGdRCMdsu5Ya2EskMyvE9ZDTqt76o"
              }
            ]
          },
          "num_comments":16,
          "thumbnail":"http://b.thumbs.redditmedia.com/2WebUh6-k9J62KP3UJ26L-ORzGrpT-3gHfyZz1AY7oM.jpg",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"link",
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vnxg5/free_eggheadio_course_learn_mobx_react_in_30/",
          "locked":false,
          "name":"t3_4vnxg5",
          "created":1470104317.0,
          "url":"https://egghead.io/courses/manage-complex-state-in-react-apps-with-mobx",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Free egghead.io course: Learn MobX + React in 30 minutes",
          "created_utc":1470075517.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":49
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"github.com",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vse46",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"repeatedly_once",
          "media":null,
          "score":2,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/59nclGR7gPbbPktRrWucnkalGA4u7zVu7sLe22wAr-4.jpg?s=ede2720c80e1339d9a5f857f556f0d66",
                  "width":400,
                  "height":400
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/59nclGR7gPbbPktRrWucnkalGA4u7zVu7sLe22wAr-4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=94754f9a4fa42c264f8cafe26efa01b0",
                    "width":108,
                    "height":108
                  },
                  {
                    "url":"https://i.redditmedia.com/59nclGR7gPbbPktRrWucnkalGA4u7zVu7sLe22wAr-4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=bb9dbec678ddd04e2e8bc1eca02c459a",
                    "width":216,
                    "height":216
                  },
                  {
                    "url":"https://i.redditmedia.com/59nclGR7gPbbPktRrWucnkalGA4u7zVu7sLe22wAr-4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=39d07560e83e471193c9b10ba1e54f64",
                    "width":320,
                    "height":320
                  }
                ],
                "variants":{

                },
                "id":"70-ANVFxSvkYVS1oB2o_U00xWPR_tT4v0cmF5tqvycE"
              }
            ]
          },
          "num_comments":0,
          "thumbnail":"http://b.thumbs.redditmedia.com/Nn9HS2xXo_74MNebv5wRCd_2sNDxbpMObeHTy_N0Fxk.jpg",
          "subreddit_id":"t5_2zldd",
          "hide_score":true,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"link",
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vse46/improve_ttfb_and_performance_of_your_universal_app/",
          "locked":false,
          "name":"t3_4vse46",
          "created":1470172853.0,
          "url":"https://github.com/walmartlabs/electrode-react-ssr-optimization",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Improve TTFB and performance of your universal app.",
          "created_utc":1470144053.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":2
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;m trying to debug a library that hooks into instantiateReactComponent.js. When the library is running I can see functions from instantiateReactComponent.js being called, specifically because the library calls it. &lt;/p&gt;\n\n&lt;p&gt;When I turn the library off, I can&amp;#39;t see any calls being made to instantiateReactComponent.js and I&amp;#39;m not sure why. Has anyone had experience in this?\nThe library in question is &lt;a href=\"https://github.com/walmartlabs/electrode-react-ssr-optimization\"&gt;https://github.com/walmartlabs/electrode-react-ssr-optimization&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;Edit: I solved it. The library was referring to it&amp;#39;s own local version of React which caused some issues as I was trying to debug my version.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"I'm trying to debug a library that hooks into instantiateReactComponent.js. When the library is running I can see functions from instantiateReactComponent.js being called, specifically because the library calls it. \n\nWhen I turn the library off, I can't see any calls being made to instantiateReactComponent.js and I'm not sure why. Has anyone had experience in this?\nThe library in question is https://github.com/walmartlabs/electrode-react-ssr-optimization\n\nEdit: I solved it. The library was referring to it's own local version of React which caused some issues as I was trying to debug my version.",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vrifk",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"repeatedly_once",
          "media":null,
          "score":2,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/59nclGR7gPbbPktRrWucnkalGA4u7zVu7sLe22wAr-4.jpg?s=ede2720c80e1339d9a5f857f556f0d66",
                  "width":400,
                  "height":400
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/59nclGR7gPbbPktRrWucnkalGA4u7zVu7sLe22wAr-4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=94754f9a4fa42c264f8cafe26efa01b0",
                    "width":108,
                    "height":108
                  },
                  {
                    "url":"https://i.redditmedia.com/59nclGR7gPbbPktRrWucnkalGA4u7zVu7sLe22wAr-4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=bb9dbec678ddd04e2e8bc1eca02c459a",
                    "width":216,
                    "height":216
                  },
                  {
                    "url":"https://i.redditmedia.com/59nclGR7gPbbPktRrWucnkalGA4u7zVu7sLe22wAr-4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=39d07560e83e471193c9b10ba1e54f64",
                    "width":320,
                    "height":320
                  }
                ],
                "variants":{

                },
                "id":"70-ANVFxSvkYVS1oB2o_U00xWPR_tT4v0cmF5tqvycE"
              }
            ]
          },
          "num_comments":0,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":1470144114.0,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"self",
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vrifk/instantiatereactcomponentjs_where_does_this_fit/",
          "locked":false,
          "name":"t3_4vrifk",
          "created":1470156325.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vrifk/instantiatereactcomponentjs_where_does_this_fit/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"instantiateReactComponent.js - Where does this fit into the lifecycle?",
          "created_utc":1470127525.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":2
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"medium.com",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vmi24",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"hb_to_ms",
          "media":null,
          "score":35,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/5Oh1qwFPwziePBbeyN8EfxS6DnsBYWQk44AMgFpzXi8.jpg?s=2d4630bf9285d3704628685e46f53361",
                  "width":480,
                  "height":737
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/5Oh1qwFPwziePBbeyN8EfxS6DnsBYWQk44AMgFpzXi8.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=cf845c935848be0e9f3d7663690fd8dd",
                    "width":108,
                    "height":165
                  },
                  {
                    "url":"https://i.redditmedia.com/5Oh1qwFPwziePBbeyN8EfxS6DnsBYWQk44AMgFpzXi8.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=41e235c20a9b080a4a5627153cebc954",
                    "width":216,
                    "height":331
                  },
                  {
                    "url":"https://i.redditmedia.com/5Oh1qwFPwziePBbeyN8EfxS6DnsBYWQk44AMgFpzXi8.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=658257b4239e0aad4e6b03577961349a",
                    "width":320,
                    "height":491
                  }
                ],
                "variants":{

                },
                "id":"L2KPTJP8d9gfVn3yUn-SKga9dXGCaQx84SKAe9cLzZo"
              }
            ]
          },
          "num_comments":1,
          "thumbnail":"http://b.thumbs.redditmedia.com/qFFpapDIFVAO0cHreoUYISFRRqJwHo5a4LgiAwxih-o.jpg",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"link",
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vmi24/react_native_animations_using_the_animated_api/",
          "locked":false,
          "name":"t3_4vmi24",
          "created":1470087136.0,
          "url":"https://medium.com/@dabit3/react-native-animations-using-the-animated-api-ebe8e0669fae#.moef3ct71",
          "author_flair_text":null,
          "quarantine":false,
          "title":"React Native Animations Using the Animated API",
          "created_utc":1470058336.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":35
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey guys! I would like to know what&amp;#39;s the best way to add auth to a preexisting \nseparate admin page that can change components from the admin page once the user is logged in&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"Hey guys! I would like to know what's the best way to add auth to a preexisting \nseparate admin page that can change components from the admin page once the user is logged in",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4voxq9",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"MaskedBandit1",
          "media":null,
          "score":6,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":3,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4voxq9/putting_admin_page_user_and_pass_auth_on_my_site/",
          "locked":false,
          "name":"t3_4voxq9",
          "created":1470116095.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4voxq9/putting_admin_page_user_and_pass_auth_on_my_site/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Putting admin page user and pass auth on my site.",
          "created_utc":1470087295.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":6
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"blog.spacelab.team",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vn9mh",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"dkhaburdzania",
          "media":null,
          "score":6,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":3,
          "thumbnail":"default",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vn9mh/4_things_for_efficient_redux/",
          "locked":false,
          "name":"t3_4vn9mh",
          "created":1470096752.0,
          "url":"https://blog.spacelab.team/4-things-for-efficient-redux-17e87b4cd6cb#.pxdv025gq",
          "author_flair_text":null,
          "quarantine":false,
          "title":"4 things for efficient Redux",
          "created_utc":1470067952.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":6
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"brightwork.io",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vn67w",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"josh_carterpdx",
          "media":null,
          "score":4,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/LO3QXnRMKnCTwvccmfIHmKOJ9j_6MKjX6GzuziE0qmA.jpg?s=8beea0d2707528f040a43786fd4dd60d",
                  "width":300,
                  "height":200
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/LO3QXnRMKnCTwvccmfIHmKOJ9j_6MKjX6GzuziE0qmA.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=d4923e84e4c963e9d0a4f97f5cb10a3e",
                    "width":108,
                    "height":72
                  },
                  {
                    "url":"https://i.redditmedia.com/LO3QXnRMKnCTwvccmfIHmKOJ9j_6MKjX6GzuziE0qmA.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=314f774d0e1c6f657f3c1de3419b7c1c",
                    "width":216,
                    "height":144
                  }
                ],
                "variants":{

                },
                "id":"dMFivqQtyn053vQg8NJADq_hCuUuyizleo-FmfbO1FI"
              }
            ]
          },
          "num_comments":0,
          "thumbnail":"http://b.thumbs.redditmedia.com/YF6BSucQ-y7c_6BrpO5RYvvJSkqk-tUf78K0hUlQx6w.jpg",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"link",
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vn67w/brightwork_a_backend_in_a_box_launched_today/",
          "locked":false,
          "name":"t3_4vn67w",
          "created":1470095652.0,
          "url":"http://brightwork.io",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Brightwork, a Backend in a Box Launched Today!",
          "created_utc":1470066852.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":4
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;So I&amp;#39;ve been learning a bit about React recently and have loved using it for a few small projects so far. I&amp;#39;m trying to see how well React could fit in with the site structure at my company, and running into a problem trying to use React without seeing a constantly increasing initial site load time.&lt;/p&gt;\n\n&lt;p&gt;Essentially, the website is a blog-type site where we have a number of different sections that people can contribute to. We have a site header/footer, a navigation sidebar, and then right now each blog post gets its own page. The header/footer/sidebar would be pretty easy to convert to React components, but I&amp;#39;m worried about the main content areas. The problem is that each blog post needs to be able to use its own markup/HTML, because plain text doesn&amp;#39;t provide the functionality we need.&lt;/p&gt;\n\n&lt;p&gt;The first thought is that, yes, we could just have people write each of their posts in JSX as React components. If we bundled and minified it right now, it probably wouldn&amp;#39;t be more than a few Mbs total, but as more blog posts get written, obviously there would never be a cap on the total bundle size.&lt;/p&gt;\n\n&lt;p&gt;So the second thought is that the structure of the site is determined by React components, and then we have a main content type component that would be used like &amp;lt;BlogPost file=&amp;#39;posts/test.html&amp;#39; /&amp;gt;, which would go out and get the required HTML in one of the lifecycle methods and render the HTML as children.&lt;/p&gt;\n\n&lt;p&gt;I know about _dangeouslySetInnerHTML, but I&amp;#39;m wondering if there&amp;#39;s anything I&amp;#39;m not thinking of, or if there are other ways people have tackled this problem when building a React app.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"So I've been learning a bit about React recently and have loved using it for a few small projects so far. I'm trying to see how well React could fit in with the site structure at my company, and running into a problem trying to use React without seeing a constantly increasing initial site load time.\n\nEssentially, the website is a blog-type site where we have a number of different sections that people can contribute to. We have a site header/footer, a navigation sidebar, and then right now each blog post gets its own page. The header/footer/sidebar would be pretty easy to convert to React components, but I'm worried about the main content areas. The problem is that each blog post needs to be able to use its own markup/HTML, because plain text doesn't provide the functionality we need.\n\nThe first thought is that, yes, we could just have people write each of their posts in JSX as React components. If we bundled and minified it right now, it probably wouldn't be more than a few Mbs total, but as more blog posts get written, obviously there would never be a cap on the total bundle size.\n\nSo the second thought is that the structure of the site is determined by React components, and then we have a main content type component that would be used like &lt;BlogPost file='posts/test.html' /&gt;, which would go out and get the required HTML in one of the lifecycle methods and render the HTML as children.\n\nI know about _dangeouslySetInnerHTML, but I'm wondering if there's anything I'm not thinking of, or if there are other ways people have tackled this problem when building a React app.",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vp9hx",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"CatchACrab",
          "media":null,
          "score":1,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":1,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vp9hx/rendering_external_markuphtml_as_children_of_a/",
          "locked":false,
          "name":"t3_4vp9hx",
          "created":1470120332.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vp9hx/rendering_external_markuphtml_as_children_of_a/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Rendering external markup/HTML as children of a react component",
          "created_utc":1470091532.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":1
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;ve been using Redux for months now and I realized that using Redux actually slows down my dev speed a lot (sorry that the title is provocative). I separated the backend and frontend completely into two repos. I use Rails on the backend and Redux on the frontend.&lt;/p&gt;\n\n&lt;p&gt;It feels very nice to be following the modern ES6 trend with React, Redux, and Babel. But these two things bother me:&lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;You have to write a LOT of code just to get CRUD right. Getting the loading state right, making sure that the frontend and backend data are always in sync, etc. is more hassle than you might imagine.&lt;/li&gt;\n&lt;li&gt;You have to worry about SSR, which is not all that simple.&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;So I went ahead and re-wrote my app in Rails and React without using Redux. Basically, I just used React to draw presentational components, and Rails controllers replaced Redux&amp;#39;s smart container. Then, I could implement the same functionality twice as fast.&lt;/p&gt;\n\n&lt;p&gt;Has using Redux slowed your development speed too? Is it really necessary?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"I've been using Redux for months now and I realized that using Redux actually slows down my dev speed a lot (sorry that the title is provocative). I separated the backend and frontend completely into two repos. I use Rails on the backend and Redux on the frontend.\n\nIt feels very nice to be following the modern ES6 trend with React, Redux, and Babel. But these two things bother me:\n\n1. You have to write a LOT of code just to get CRUD right. Getting the loading state right, making sure that the frontend and backend data are always in sync, etc. is more hassle than you might imagine.\n2. You have to worry about SSR, which is not all that simple.\n\nSo I went ahead and re-wrote my app in Rails and React without using Redux. Basically, I just used React to draw presentational components, and Rails controllers replaced Redux's smart container. Then, I could implement the same functionality twice as fast.\n\nHas using Redux slowed your development speed too? Is it really necessary?",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vqp3u",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"woniesong92",
          "media":null,
          "score":0,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":4,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vqp3u/redux_slows_down_your_development_speed/",
          "locked":false,
          "name":"t3_4vqp3u",
          "created":1470140309.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vqp3u/redux_slows_down_your_development_speed/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Redux slows down your development speed",
          "created_utc":1470111509.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":0
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Plus, any great tutorials you have studied from?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"Plus, any great tutorials you have studied from?",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vm3pu",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"theendorthebeginning",
          "media":null,
          "score":2,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":20,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vm3pu/beginner_learning_react_should_i_focus_on_es5_or/",
          "locked":false,
          "name":"t3_4vm3pu",
          "created":1470081334.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vm3pu/beginner_learning_react_should_i_focus_on_es5_or/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Beginner learning React. Should I focus on ES5 or ES6?",
          "created_utc":1470052534.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":2
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"medium.com",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vn0o6",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"nunopinheiro",
          "media":null,
          "score":1,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":0,
          "thumbnail":"default",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vn0o6/accessing_react_proptypes_metadata/",
          "locked":false,
          "name":"t3_4vn0o6",
          "created":1470093811.0,
          "url":"https://medium.com/@nunogrilopinheiro/accessing-react-proptypes-meta-data-45b3465abda7",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Accessing React PropTypes Meta-Data",
          "created_utc":1470065011.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":1
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"blog.153.io",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vlnyz",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"quarterto",
          "media":null,
          "score":1,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":0,
          "thumbnail":"default",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vlnyz/a_crash_course_in_react/",
          "locked":false,
          "name":"t3_4vlnyz",
          "created":1470072701.0,
          "url":"http://blog.153.io/2016/07/31/react-crash-course/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"A Crash Course in React",
          "created_utc":1470043901.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":1
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"leanpub.com",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vi5l7",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"manavsehgal",
          "media":null,
          "score":14,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/4m-pSg5XscuLfv2ZH8BU_8kXXUN10dqqascqQJLdA_I.jpg?s=f7350eabd58988ad516c261fba495890",
                  "width":936,
                  "height":619
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/4m-pSg5XscuLfv2ZH8BU_8kXXUN10dqqascqQJLdA_I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=c6833142a2e7e3fc6eb7d8b191b45db6",
                    "width":108,
                    "height":71
                  },
                  {
                    "url":"https://i.redditmedia.com/4m-pSg5XscuLfv2ZH8BU_8kXXUN10dqqascqQJLdA_I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=7880f4b654cee443b538abd9812acd74",
                    "width":216,
                    "height":142
                  },
                  {
                    "url":"https://i.redditmedia.com/4m-pSg5XscuLfv2ZH8BU_8kXXUN10dqqascqQJLdA_I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=496b38d90a7505eea1f403adde9de933",
                    "width":320,
                    "height":211
                  },
                  {
                    "url":"https://i.redditmedia.com/4m-pSg5XscuLfv2ZH8BU_8kXXUN10dqqascqQJLdA_I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=9f04e852ba4027fd54b5c5496163b23c",
                    "width":640,
                    "height":423
                  }
                ],
                "variants":{

                },
                "id":"E_NKM_va9DpzFBRjzWXrI9sor_UmdTzIcC-S1YbMq-k"
              }
            ]
          },
          "num_comments":0,
          "thumbnail":"http://b.thumbs.redditmedia.com/Lu0T2d8pTj4pz9Q2aQ9MiqKkR1LNJMQUbxJF6QvYG6E.jpg",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"link",
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vi5l7/easy_start_react_using_create_react_app_react/",
          "locked":false,
          "name":"t3_4vi5l7",
          "created":1470016450.0,
          "url":"https://leanpub.com/reacteshop/read",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Easy Start React using Create React App, React Bootstrap, and Firebase.",
          "created_utc":1469987650.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":14
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;m attempting to replicate the functionality on Facebook where you can click on an image and it opens up in a browser/carousel that lets you switch between multiple images. &lt;/p&gt;\n\n&lt;p&gt;I &lt;a href=\"http://stackoverflow.com/questions/38678894/triggering-a-dynamic-react-element-to-appear-on-click\"&gt;outlined the question here&lt;/a&gt; with little luck, but I&amp;#39;m wondering how to even trigger a react element to pop up on click in Rails. &lt;/p&gt;\n\n&lt;p&gt;Any input appreciated, thanks!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"I'm attempting to replicate the functionality on Facebook where you can click on an image and it opens up in a browser/carousel that lets you switch between multiple images. \n\nI [outlined the question here](http://stackoverflow.com/questions/38678894/triggering-a-dynamic-react-element-to-appear-on-click) with little luck, but I'm wondering how to even trigger a react element to pop up on click in Rails. \n\nAny input appreciated, thanks!",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vjq5n",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"UnderwaterPenguin",
          "media":null,
          "score":2,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/yzSfTlKTSYGpEXeFgyDvHlfoLGOFQJqPuH_Y38RBz2U.jpg?s=5771b03e94f56162bcafaf1079f2a1e7",
                  "width":316,
                  "height":316
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/yzSfTlKTSYGpEXeFgyDvHlfoLGOFQJqPuH_Y38RBz2U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=9189a7b196263db4825e3ab0c948e796",
                    "width":108,
                    "height":108
                  },
                  {
                    "url":"https://i.redditmedia.com/yzSfTlKTSYGpEXeFgyDvHlfoLGOFQJqPuH_Y38RBz2U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=c442ba677155996a0a49f51a400124b1",
                    "width":216,
                    "height":216
                  }
                ],
                "variants":{

                },
                "id":"nfayPavSUB5ngYv6-19UHNBThsXfcLIDQl4HkEe3Cv0"
              }
            ]
          },
          "num_comments":3,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"self",
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vjq5n/replicating_facebooks_image_browser_carousel/",
          "locked":false,
          "name":"t3_4vjq5n",
          "created":1470037763.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vjq5n/replicating_facebooks_image_browser_carousel/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Replicating Facebook's image browser / carousel functionality",
          "created_utc":1470008963.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":2
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"react-next.com",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vj0yg",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"AloneInThePark",
          "media":null,
          "score":2,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/Z4AYvTVQ23yKoDLxoTkyiNM16_HOrmElMKoEVUCemF0.jpg?s=bb6a8adacf349b736924ed465101ad02",
                  "width":1162,
                  "height":613
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/Z4AYvTVQ23yKoDLxoTkyiNM16_HOrmElMKoEVUCemF0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=c42ae5823db1c430aabc3b801323c50d",
                    "width":108,
                    "height":56
                  },
                  {
                    "url":"https://i.redditmedia.com/Z4AYvTVQ23yKoDLxoTkyiNM16_HOrmElMKoEVUCemF0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=ab70c089dc99b16027e53a6bafe6c61e",
                    "width":216,
                    "height":113
                  },
                  {
                    "url":"https://i.redditmedia.com/Z4AYvTVQ23yKoDLxoTkyiNM16_HOrmElMKoEVUCemF0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=ae2d84711f391ace544bb7932ec93c27",
                    "width":320,
                    "height":168
                  },
                  {
                    "url":"https://i.redditmedia.com/Z4AYvTVQ23yKoDLxoTkyiNM16_HOrmElMKoEVUCemF0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=6fc35e86c339edc85fe77a4553c87ecc",
                    "width":640,
                    "height":337
                  },
                  {
                    "url":"https://i.redditmedia.com/Z4AYvTVQ23yKoDLxoTkyiNM16_HOrmElMKoEVUCemF0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=c0e19fd8c52dc4d6d78c236bfc29b30c",
                    "width":960,
                    "height":506
                  },
                  {
                    "url":"https://i.redditmedia.com/Z4AYvTVQ23yKoDLxoTkyiNM16_HOrmElMKoEVUCemF0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=6e91ae2511c9de6901ce9a27df22729e",
                    "width":1080,
                    "height":569
                  }
                ],
                "variants":{

                },
                "id":"6h1ZEP2D-qL_oXRAPWJR2eLhA6yvayeUvJZpl30Npaw"
              }
            ]
          },
          "num_comments":2,
          "thumbnail":"http://b.thumbs.redditmedia.com/nj-FVLhXqbRtx4C0SLJD_8jDj8BguM4RwBWiK2n6fBo.jpg",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"link",
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vj0yg/reactnext_published_an_amazing_agenda_and/",
          "locked":false,
          "name":"t3_4vj0yg",
          "created":1470027965.0,
          "url":"http://react-next.com/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"ReactNext published an amazing agenda and extended tier 1 ticket sale",
          "created_utc":1469999165.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":2
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hi,&lt;/p&gt;\n\n&lt;p&gt;I&amp;#39;m looking for a good boilerplate to use with Redux and Redux-Auth. I was using the react-redux-starter-kit by daezuko but I found it difficult to troubleshoot errors, the CSS was weird and I couldn&amp;#39;t figure out why Redux-Auth wouldn&amp;#39;t work.&lt;/p&gt;\n\n&lt;p&gt;Should I do it myself or is there something proper out there? What are you using?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"Hi,\n\nI'm looking for a good boilerplate to use with Redux and Redux-Auth. I was using the react-redux-starter-kit by daezuko but I found it difficult to troubleshoot errors, the CSS was weird and I couldn't figure out why Redux-Auth wouldn't work.\n\nShould I do it myself or is there something proper out there? What are you using?",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vguxe",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"Bobgle",
          "media":null,
          "score":5,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":9,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vguxe/boilerplate_for_react_redux_reduxauth/",
          "locked":false,
          "name":"t3_4vguxe",
          "created":1469996497.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vguxe/boilerplate_for_react_redux_reduxauth/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"boilerplate for React + Redux + Redux-Auth?",
          "created_utc":1469967697.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":5
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;m currently working on a front end app that uses React. It&amp;#39;s a fairly complex app that&amp;#39;s been worked on by multiple developers over a few years, most of who are no longer around.&lt;/p&gt;\n\n&lt;p&gt;It doesn&amp;#39;t currently use a cohesive state management system. Most of the components are built in an OOP style with localized state. There&amp;#39;s not a lot of consistency in the app: you can clearly tell that some parts of the app are written in a completely different style from other parts.&lt;/p&gt;\n\n&lt;p&gt;After working on this app for about a month, I&amp;#39;m finding it annoying to deal with the problems that come with this style of building apps, many of which I think would be solved by Redux. When I build a feature or fix a bug, I feel like I spend an unnecessary amount of time piecing together the state of the app across multiple components with console logs, debugger statements, and binding things to the window so I can inspect them. And even after I&amp;#39;m done with that I still can&amp;#39;t be sure if I was 100% thorough and that there isn&amp;#39;t another part of the app reaching in to mutate the state of one of the components I&amp;#39;m working with.&lt;/p&gt;\n\n&lt;p&gt;In the future there will be a need to add large new features that can be fairly modularized. I&amp;#39;m considering using Redux in them, but I&amp;#39;m unsure if it will just add more complexity for too little benefit.&lt;/p&gt;\n\n&lt;p&gt;Does anyone have experience with this type of thing and wouldn&amp;#39;t mind offering me advice?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"I'm currently working on a front end app that uses React. It's a fairly complex app that's been worked on by multiple developers over a few years, most of who are no longer around.\n\nIt doesn't currently use a cohesive state management system. Most of the components are built in an OOP style with localized state. There's not a lot of consistency in the app: you can clearly tell that some parts of the app are written in a completely different style from other parts.\n\nAfter working on this app for about a month, I'm finding it annoying to deal with the problems that come with this style of building apps, many of which I think would be solved by Redux. When I build a feature or fix a bug, I feel like I spend an unnecessary amount of time piecing together the state of the app across multiple components with console logs, debugger statements, and binding things to the window so I can inspect them. And even after I'm done with that I still can't be sure if I was 100% thorough and that there isn't another part of the app reaching in to mutate the state of one of the components I'm working with.\n\nIn the future there will be a need to add large new features that can be fairly modularized. I'm considering using Redux in them, but I'm unsure if it will just add more complexity for too little benefit.\n\nDoes anyone have experience with this type of thing and wouldn't mind offering me advice?",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vig2n",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"kindlebluemoon",
          "media":null,
          "score":2,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":5,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vig2n/i_want_to_use_redux_at_work_in_a_preexisting_app/",
          "locked":false,
          "name":"t3_4vig2n",
          "created":1470020256.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vig2n/i_want_to_use_redux_at_work_in_a_preexisting_app/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"I want to use Redux at work in a preexisting app but I don't know if it's appropriate",
          "created_utc":1469991456.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":2
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"github.com",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vixyo",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"dazld",
          "media":null,
          "score":0,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/Zvt8yUgBdoJ4nUvWuKEzrL1KnVd2jlWX3DTZ7fNETas.jpg?s=71614cfcc3d9aeaa5d6f2c0a3eda1b9a",
                  "width":400,
                  "height":400
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/Zvt8yUgBdoJ4nUvWuKEzrL1KnVd2jlWX3DTZ7fNETas.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=88436be80fcb68caeab2cf64b2db8945",
                    "width":108,
                    "height":108
                  },
                  {
                    "url":"https://i.redditmedia.com/Zvt8yUgBdoJ4nUvWuKEzrL1KnVd2jlWX3DTZ7fNETas.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=c96f4e78d85e6f8a8e5d4f9c1273e83e",
                    "width":216,
                    "height":216
                  },
                  {
                    "url":"https://i.redditmedia.com/Zvt8yUgBdoJ4nUvWuKEzrL1KnVd2jlWX3DTZ7fNETas.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=82f13e0ceb5f58687fb7543c2b659a30",
                    "width":320,
                    "height":320
                  }
                ],
                "variants":{

                },
                "id":"HNUf9jFWbr3xDdZ6TAbQteSIDxRUBdyfhCc6hdMGByk"
              }
            ]
          },
          "num_comments":1,
          "thumbnail":"http://b.thumbs.redditmedia.com/YwWlmk06NnK5m8CObk5wS0xlqhtlRmW1tw6ii_wtqlE.jpg",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"link",
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vixyo/universal_react_redux_gulp_browserify_generator/",
          "locked":false,
          "name":"t3_4vixyo",
          "created":1470026862.0,
          "url":"https://github.com/dazld/generator-cairn",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Universal React / redux / Gulp &amp; Browserify generator",
          "created_utc":1469998062.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":0
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"sheshbabu.com",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vgd0m",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"sheshbabu",
          "media":null,
          "score":5,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":0,
          "thumbnail":"default",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vgd0m/using_optimizely_with_react/",
          "locked":false,
          "name":"t3_4vgd0m",
          "created":1469984606.0,
          "url":"http://www.sheshbabu.com/posts/using-optimizely-with-react/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"Using Optimizely with React",
          "created_utc":1469955806.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":5
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;One of the things I&amp;#39;ve picked up in the last half a year of writing a pretty large scale React app is that basically all of the difficulty of writing a React app comes from figuring out how to manage and structure state. And especially given all the talk lately about &amp;quot;state being harmful&amp;quot; or what have you, it seems this is a bit of a hot topic. So for my talk at ReactJS Tokyo this week, I presented this app which doesn&amp;#39;t use any component state:&lt;/p&gt;\n\n&lt;pre&gt;&lt;code&gt;class CommentForm extends React.Component {\n    static propTypes = {\n        value: React.PropTypes.object.isRequired,\n        onChange: React.PropTypes.func.isRequired,\n    }\n\n    handleChange(field, e) {\n        this.props.onChange({\n            ...this.props.value,\n            [field]: e.target.value,\n        })\n    }\n\n    render() {\n        return (\n            &amp;lt;div&amp;gt;\n                &amp;lt;input\n                    placeholder=&amp;quot;Name&amp;quot;\n                    value={this.props.value.name}\n                    onChange={this.handleChange.bind(this, &amp;#39;name&amp;#39;)}\n                /&amp;gt;\n                &amp;lt;input\n                    placeholder=&amp;quot;Message&amp;quot;\n                    value={this.props.value.message}\n                    onChange={this.handleChange.bind(this, &amp;#39;message&amp;#39;)}\n                /&amp;gt;\n            &amp;lt;/div&amp;gt;\n        )\n    }\n}\n\n// Handle updated values by re-rendering the app\nfunction render(value) {\n    ReactDOM.render(\n        &amp;lt;CommentForm\n            value={value}\n            onChange={render}\n        /&amp;gt;,\n        document.getElementById(&amp;quot;react-app&amp;quot;)\n    )\n}\n\n// Initialise the app by rendering it\nrender({\n    name: &amp;quot;James K Nelson&amp;quot;,\n    message: &amp;quot;Look Ma, No Component State&amp;quot;,\n})\n&lt;/code&gt;&lt;/pre&gt;\n\n&lt;p&gt;If you&amp;#39;d like to see more in depth discussion on this snippet, you can see the &lt;a href=\"http://jamesknelson.com/state-react-1-stateless-react-app/\"&gt;article on it&lt;/a&gt;. But the questions I wanted to ask here are:&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;Does this app have state? If so, where is it?&lt;/li&gt;\n&lt;li&gt;If state is harmful, why don&amp;#39;t people write apps like this. Or if you do, let us know.&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;I have my own answers to these questions, but thought it&amp;#39;d be interesting to hear what people here think. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"One of the things I've picked up in the last half a year of writing a pretty large scale React app is that basically all of the difficulty of writing a React app comes from figuring out how to manage and structure state. And especially given all the talk lately about \"state being harmful\" or what have you, it seems this is a bit of a hot topic. So for my talk at ReactJS Tokyo this week, I presented this app which doesn't use any component state:\n\n    class CommentForm extends React.Component {\n        static propTypes = {\n            value: React.PropTypes.object.isRequired,\n            onChange: React.PropTypes.func.isRequired,\n        }\n\n        handleChange(field, e) {\n            this.props.onChange({\n                ...this.props.value,\n                [field]: e.target.value,\n            })\n        }\n\n        render() {\n            return (\n                &lt;div&gt;\n                    &lt;input\n                        placeholder=\"Name\"\n                        value={this.props.value.name}\n                        onChange={this.handleChange.bind(this, 'name')}\n                    /&gt;\n                    &lt;input\n                        placeholder=\"Message\"\n                        value={this.props.value.message}\n                        onChange={this.handleChange.bind(this, 'message')}\n                    /&gt;\n                &lt;/div&gt;\n            )\n        }\n    }\n    \n    // Handle updated values by re-rendering the app\n    function render(value) {\n        ReactDOM.render(\n            &lt;CommentForm\n                value={value}\n                onChange={render}\n            /&gt;,\n            document.getElementById(\"react-app\")\n        )\n    }\n    \n    // Initialise the app by rendering it\n    render({\n        name: \"James K Nelson\",\n        message: \"Look Ma, No Component State\",\n    })\n\nIf you'd like to see more in depth discussion on this snippet, you can see the [article on it](http://jamesknelson.com/state-react-1-stateless-react-app/). But the questions I wanted to ask here are:\n\n- Does this app have state? If so, where is it?\n- If state is harmful, why don't people write apps like this. Or if you do, let us know.\n\nI have my own answers to these questions, but thought it'd be interesting to hear what people here think. ",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vg4xv",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"jamesknelson",
          "media":null,
          "score":7,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/MK-h1G9OZHe3oWi2VAMV0meOQCoghDauf8qB8YdGo_A.jpg?s=dda6f87aa29ee023be958db5c6ca8b65",
                  "width":226,
                  "height":226
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/MK-h1G9OZHe3oWi2VAMV0meOQCoghDauf8qB8YdGo_A.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=5455d0d4fee36a71cc4e9d66cdaa5174",
                    "width":108,
                    "height":108
                  },
                  {
                    "url":"https://i.redditmedia.com/MK-h1G9OZHe3oWi2VAMV0meOQCoghDauf8qB8YdGo_A.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=6d66b6bf655f4c03e80c5cfade096a06",
                    "width":216,
                    "height":216
                  }
                ],
                "variants":{

                },
                "id":"Eg8P1xHUxkMrRfO5Yps_BMwLdlfyTN921AvALwoPhuw"
              }
            ]
          },
          "num_comments":13,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"self",
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vg4xv/a_stateless_react_app/",
          "locked":false,
          "name":"t3_4vg4xv",
          "created":1469978840.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vg4xv/a_stateless_react_app/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"A Stateless React App?",
          "created_utc":1469950040.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":7
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If I have a component which in componentDidMount needs to dispatch an action to request data from server which is needed for rendering of that component how to handle asynchronous nature of that request?&lt;/p&gt;\n\n&lt;p&gt;Should I have something like this in my render: (I am using flux pattern so component will be notified when store receives data)&lt;/p&gt;\n\n&lt;pre&gt;&lt;code&gt;render: function() {\n    var data = store.get();\n    if (!data) return { null; }\n   // otherwise do actual render method\n&lt;/code&gt;&lt;/pre&gt;\n\n&lt;p&gt;Is this valid? I guess in this case I have to hope fetching happens fast, otherwise user will get an empty page until response.&lt;/p&gt;\n\n&lt;p&gt;Another case is what would happen if some other component was supposed to fetch data but user refreshed the page so it&amp;#39;s no longer in store. Should I check in componentDidMount if data exists and if not make another request to server? Or is there a better way to handle this?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"If I have a component which in componentDidMount needs to dispatch an action to request data from server which is needed for rendering of that component how to handle asynchronous nature of that request?\n\nShould I have something like this in my render: (I am using flux pattern so component will be notified when store receives data)\n\n    render: function() {\n        var data = store.get();\n        if (!data) return { null; }\n       // otherwise do actual render method\n\nIs this valid? I guess in this case I have to hope fetching happens fast, otherwise user will get an empty page until response.\n\nAnother case is what would happen if some other component was supposed to fetch data but user refreshed the page so it's no longer in store. Should I check in componentDidMount if data exists and if not make another request to server? Or is there a better way to handle this?",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vho0q",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"PM_ME_SMILE_",
          "media":null,
          "score":1,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":6,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vho0q/data_fetching_and_rendering/",
          "locked":false,
          "name":"t3_4vho0q",
          "created":1470009801.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vho0q/data_fetching_and_rendering/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"data fetching and rendering",
          "created_utc":1469981001.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":1
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"medium.com",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":null,
          "selftext":"",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4ve76h",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"taion",
          "media":null,
          "score":17,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "num_comments":7,
          "thumbnail":"default",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":false,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "stickied":false,
          "from":null,
          "is_self":false,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4ve76h/the_problem_with_cssinjs_circa_mid2016/",
          "locked":false,
          "name":"t3_4ve76h",
          "created":1469944587.0,
          "url":"https://medium.com/@taion/the-problem-with-css-in-js-circa-mid-2016-14060e69bf68",
          "author_flair_text":null,
          "quarantine":false,
          "title":"The Problem with CSS-In-JS, circa Mid-2016",
          "created_utc":1469915787.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":17
        }
      },
      {
        "kind":"t3",
        "data":{
          "domain":"self.reactjs",
          "banned_by":null,
          "media_embed":{

          },
          "subreddit":"reactjs",
          "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;&lt;a href=\"https://www.npmjs.com/package/generator-react-webpack-scaffold\"&gt;https://www.npmjs.com/package/generator-react-webpack-scaffold&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;Now the generator allows you to enable/disable localization feature for your React project. Added examples and test cases, hope that will help you quickly get your React project up and running.&lt;/p&gt;\n\n&lt;p&gt;Going to support more features like Redux in future release.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext":"https://www.npmjs.com/package/generator-react-webpack-scaffold\n\nNow the generator allows you to enable/disable localization feature for your React project. Added examples and test cases, hope that will help you quickly get your React project up and running.\n\nGoing to support more features like Redux in future release.",
          "likes":null,
          "suggested_sort":null,
          "user_reports":[

          ],
          "secure_media":null,
          "link_flair_text":null,
          "id":"4vfppa",
          "from_kind":null,
          "gilded":0,
          "archived":false,
          "clicked":false,
          "report_reasons":null,
          "author":"jeantimex",
          "media":null,
          "score":2,
          "approved_by":null,
          "over_18":false,
          "hidden":false,
          "preview":{
            "images":[
              {
                "source":{
                  "url":"https://i.redditmedia.com/sr7XqdeKF73E4m8CFm57jK-VSCmixf5xr3cX1tdw1SY.jpg?s=6101ad50f9972dfc03ec71b42f782ec6",
                  "width":1200,
                  "height":630
                },
                "resolutions":[
                  {
                    "url":"https://i.redditmedia.com/sr7XqdeKF73E4m8CFm57jK-VSCmixf5xr3cX1tdw1SY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=5fe4e5bdef475fc7b11f414eeb19d5e8",
                    "width":108,
                    "height":56
                  },
                  {
                    "url":"https://i.redditmedia.com/sr7XqdeKF73E4m8CFm57jK-VSCmixf5xr3cX1tdw1SY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=c38d3be8e46fc96c55c8684c27773fb2",
                    "width":216,
                    "height":113
                  },
                  {
                    "url":"https://i.redditmedia.com/sr7XqdeKF73E4m8CFm57jK-VSCmixf5xr3cX1tdw1SY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=5fac83db7515e4c6e70f1e46849dfeed",
                    "width":320,
                    "height":168
                  },
                  {
                    "url":"https://i.redditmedia.com/sr7XqdeKF73E4m8CFm57jK-VSCmixf5xr3cX1tdw1SY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=737e6b98dcbe9518b5120fd9fafe69b5",
                    "width":640,
                    "height":336
                  },
                  {
                    "url":"https://i.redditmedia.com/sr7XqdeKF73E4m8CFm57jK-VSCmixf5xr3cX1tdw1SY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=eb7804a8797cd0789a503c060f1f3bfb",
                    "width":960,
                    "height":504
                  },
                  {
                    "url":"https://i.redditmedia.com/sr7XqdeKF73E4m8CFm57jK-VSCmixf5xr3cX1tdw1SY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=c0b40e94611cffa070a477c5f333d90d",
                    "width":1080,
                    "height":567
                  }
                ],
                "variants":{

                },
                "id":"3CAm7f2euOP7diXidheIHavSdc1loh3U46B-FOssKu4"
              }
            ]
          },
          "num_comments":2,
          "thumbnail":"self",
          "subreddit_id":"t5_2zldd",
          "hide_score":false,
          "edited":1469986848.0,
          "link_flair_css_class":null,
          "author_flair_css_class":null,
          "downs":0,
          "secure_media_embed":{

          },
          "saved":false,
          "removal_reason":null,
          "post_hint":"self",
          "stickied":false,
          "from":null,
          "is_self":true,
          "from_id":null,
          "permalink":"/r/reactjs/comments/4vfppa/react_webpack_generator_is_updated/",
          "locked":false,
          "name":"t3_4vfppa",
          "created":1469969174.0,
          "url":"https://www.reddit.com/r/reactjs/comments/4vfppa/react_webpack_generator_is_updated/",
          "author_flair_text":null,
          "quarantine":false,
          "title":"React Webpack Generator is updated",
          "created_utc":1469940374.0,
          "distinguished":null,
          "mod_reports":[

          ],
          "visited":false,
          "num_reports":null,
          "ups":2
        }
      }
    ],
    "after":"t3_4vfppa",
    "before":null
  }
}
